version: "3.8"

services:
    app:
        build: .
        ports:
            - 3333:3333
        command: yarn dev:server
        volumes: 
            - .:/usr/src/app
        env_file:
            - .env